name: Docker Build & Release

on:
  release:
    types: [created]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Overwrite UI
        run: |
          ls -alF
          rm -rf ./web/*
          curl -fsSL github.com/pingdongyi/webshark-ui/releases/latest/download/latest.zip -O
          unzip latest.zip -d ./web
          
      - name: Log in to the Container registry
        uses: docker/login-action@v2.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3.0.0
        with:
          context: .
          push: true
          tags: |
             ghcr.io/pingdongyi/webshark:latest
             ghcr.io/pingdongyi/webshark:${{ github.event.release.tag_name }}
